// flow-typed signature: 6911a119683f31114059e78cedb0e7a0
// flow-typed version: <<STUB>>/csv-parser_v^1.11.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-parser/bench' {
  declare module.exports: any;
}

declare module 'csv-parser/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-parser/bench.js' {
  declare module.exports: $Exports<'csv-parser/bench'>;
}
declare module 'csv-parser/bin.js' {
  declare module.exports: $Exports<'csv-parser/bin'>;
}
declare module 'csv-parser/index' {
  declare module.exports: $Exports<'csv-parser'>;
}
declare module 'csv-parser/index.js' {
  declare module.exports: $Exports<'csv-parser'>;
}
