// flow-typed signature: 3bcaa5ad1723eb8ce9aa77976ba8edd2
// flow-typed version: <<STUB>>/js-csp_v^0.8.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-csp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-csp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-csp/build/csp.min' {
  declare module.exports: any;
}

declare module 'js-csp/es/csp.core' {
  declare module.exports: any;
}

declare module 'js-csp/es/csp' {
  declare module.exports: any;
}

declare module 'js-csp/es/csp.operations' {
  declare module.exports: any;
}

declare module 'js-csp/es/csp.test-helpers' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/boxes' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/buffers' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/channels' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/dispatch' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/handlers' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/instruction' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/process' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/results' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/select' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/timers' {
  declare module.exports: any;
}

declare module 'js-csp/es/impl/utils' {
  declare module.exports: any;
}

declare module 'js-csp/lib/csp.core' {
  declare module.exports: any;
}

declare module 'js-csp/lib/csp' {
  declare module.exports: any;
}

declare module 'js-csp/lib/csp.operations' {
  declare module.exports: any;
}

declare module 'js-csp/lib/csp.test-helpers' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/boxes' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/buffers' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/channels' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/dispatch' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/handlers' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/instruction' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/process' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/results' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/select' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/timers' {
  declare module.exports: any;
}

declare module 'js-csp/lib/impl/utils' {
  declare module.exports: any;
}

declare module 'js-csp/src/csp.core' {
  declare module.exports: any;
}

declare module 'js-csp/src/csp' {
  declare module.exports: any;
}

declare module 'js-csp/src/csp.operations' {
  declare module.exports: any;
}

declare module 'js-csp/src/csp.test-helpers' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/boxes' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/buffers' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/channels' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/dispatch' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/handlers' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/instruction' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/process' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/results' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/select' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/timers' {
  declare module.exports: any;
}

declare module 'js-csp/src/impl/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-csp/build/csp.min.js' {
  declare module.exports: $Exports<'js-csp/build/csp.min'>;
}
declare module 'js-csp/es/csp.core.js' {
  declare module.exports: $Exports<'js-csp/es/csp.core'>;
}
declare module 'js-csp/es/csp.js' {
  declare module.exports: $Exports<'js-csp/es/csp'>;
}
declare module 'js-csp/es/csp.operations.js' {
  declare module.exports: $Exports<'js-csp/es/csp.operations'>;
}
declare module 'js-csp/es/csp.test-helpers.js' {
  declare module.exports: $Exports<'js-csp/es/csp.test-helpers'>;
}
declare module 'js-csp/es/impl/boxes.js' {
  declare module.exports: $Exports<'js-csp/es/impl/boxes'>;
}
declare module 'js-csp/es/impl/buffers.js' {
  declare module.exports: $Exports<'js-csp/es/impl/buffers'>;
}
declare module 'js-csp/es/impl/channels.js' {
  declare module.exports: $Exports<'js-csp/es/impl/channels'>;
}
declare module 'js-csp/es/impl/dispatch.js' {
  declare module.exports: $Exports<'js-csp/es/impl/dispatch'>;
}
declare module 'js-csp/es/impl/handlers.js' {
  declare module.exports: $Exports<'js-csp/es/impl/handlers'>;
}
declare module 'js-csp/es/impl/instruction.js' {
  declare module.exports: $Exports<'js-csp/es/impl/instruction'>;
}
declare module 'js-csp/es/impl/process.js' {
  declare module.exports: $Exports<'js-csp/es/impl/process'>;
}
declare module 'js-csp/es/impl/results.js' {
  declare module.exports: $Exports<'js-csp/es/impl/results'>;
}
declare module 'js-csp/es/impl/select.js' {
  declare module.exports: $Exports<'js-csp/es/impl/select'>;
}
declare module 'js-csp/es/impl/timers.js' {
  declare module.exports: $Exports<'js-csp/es/impl/timers'>;
}
declare module 'js-csp/es/impl/utils.js' {
  declare module.exports: $Exports<'js-csp/es/impl/utils'>;
}
declare module 'js-csp/lib/csp.core.js' {
  declare module.exports: $Exports<'js-csp/lib/csp.core'>;
}
declare module 'js-csp/lib/csp.js' {
  declare module.exports: $Exports<'js-csp/lib/csp'>;
}
declare module 'js-csp/lib/csp.operations.js' {
  declare module.exports: $Exports<'js-csp/lib/csp.operations'>;
}
declare module 'js-csp/lib/csp.test-helpers.js' {
  declare module.exports: $Exports<'js-csp/lib/csp.test-helpers'>;
}
declare module 'js-csp/lib/impl/boxes.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/boxes'>;
}
declare module 'js-csp/lib/impl/buffers.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/buffers'>;
}
declare module 'js-csp/lib/impl/channels.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/channels'>;
}
declare module 'js-csp/lib/impl/dispatch.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/dispatch'>;
}
declare module 'js-csp/lib/impl/handlers.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/handlers'>;
}
declare module 'js-csp/lib/impl/instruction.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/instruction'>;
}
declare module 'js-csp/lib/impl/process.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/process'>;
}
declare module 'js-csp/lib/impl/results.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/results'>;
}
declare module 'js-csp/lib/impl/select.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/select'>;
}
declare module 'js-csp/lib/impl/timers.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/timers'>;
}
declare module 'js-csp/lib/impl/utils.js' {
  declare module.exports: $Exports<'js-csp/lib/impl/utils'>;
}
declare module 'js-csp/src/csp.core.js' {
  declare module.exports: $Exports<'js-csp/src/csp.core'>;
}
declare module 'js-csp/src/csp.js' {
  declare module.exports: $Exports<'js-csp/src/csp'>;
}
declare module 'js-csp/src/csp.operations.js' {
  declare module.exports: $Exports<'js-csp/src/csp.operations'>;
}
declare module 'js-csp/src/csp.test-helpers.js' {
  declare module.exports: $Exports<'js-csp/src/csp.test-helpers'>;
}
declare module 'js-csp/src/impl/boxes.js' {
  declare module.exports: $Exports<'js-csp/src/impl/boxes'>;
}
declare module 'js-csp/src/impl/buffers.js' {
  declare module.exports: $Exports<'js-csp/src/impl/buffers'>;
}
declare module 'js-csp/src/impl/channels.js' {
  declare module.exports: $Exports<'js-csp/src/impl/channels'>;
}
declare module 'js-csp/src/impl/dispatch.js' {
  declare module.exports: $Exports<'js-csp/src/impl/dispatch'>;
}
declare module 'js-csp/src/impl/handlers.js' {
  declare module.exports: $Exports<'js-csp/src/impl/handlers'>;
}
declare module 'js-csp/src/impl/instruction.js' {
  declare module.exports: $Exports<'js-csp/src/impl/instruction'>;
}
declare module 'js-csp/src/impl/process.js' {
  declare module.exports: $Exports<'js-csp/src/impl/process'>;
}
declare module 'js-csp/src/impl/results.js' {
  declare module.exports: $Exports<'js-csp/src/impl/results'>;
}
declare module 'js-csp/src/impl/select.js' {
  declare module.exports: $Exports<'js-csp/src/impl/select'>;
}
declare module 'js-csp/src/impl/timers.js' {
  declare module.exports: $Exports<'js-csp/src/impl/timers'>;
}
declare module 'js-csp/src/impl/utils.js' {
  declare module.exports: $Exports<'js-csp/src/impl/utils'>;
}
