// flow-typed signature: 5f632f7d64e3746324ca009421075170
// flow-typed version: <<STUB>>/tdigest_v^0.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tdigest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tdigest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tdigest/dist/tdigest' {
  declare module.exports: any;
}

declare module 'tdigest/distributions' {
  declare module.exports: any;
}

declare module 'tdigest/example' {
  declare module.exports: any;
}

declare module 'tdigest/gruntfile' {
  declare module.exports: any;
}

declare module 'tdigest/specs/digest.spec' {
  declare module.exports: any;
}

declare module 'tdigest/specs/discrete.spec' {
  declare module.exports: any;
}

declare module 'tdigest/specs/tdigest.spec' {
  declare module.exports: any;
}

declare module 'tdigest/tdigest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tdigest/dist/tdigest.js' {
  declare module.exports: $Exports<'tdigest/dist/tdigest'>;
}
declare module 'tdigest/distributions.js' {
  declare module.exports: $Exports<'tdigest/distributions'>;
}
declare module 'tdigest/example.js' {
  declare module.exports: $Exports<'tdigest/example'>;
}
declare module 'tdigest/gruntfile.js' {
  declare module.exports: $Exports<'tdigest/gruntfile'>;
}
declare module 'tdigest/specs/digest.spec.js' {
  declare module.exports: $Exports<'tdigest/specs/digest.spec'>;
}
declare module 'tdigest/specs/discrete.spec.js' {
  declare module.exports: $Exports<'tdigest/specs/discrete.spec'>;
}
declare module 'tdigest/specs/tdigest.spec.js' {
  declare module.exports: $Exports<'tdigest/specs/tdigest.spec'>;
}
declare module 'tdigest/tdigest.js' {
  declare module.exports: $Exports<'tdigest/tdigest'>;
}
